### ISSUE TITLE
Associating translated versions is broken

### ISSUE THREAD

**Issue by d-packs** [aurovrata/cf7-polylang#6]
I select the desired translation (red ellipse), then click save. The translation field (red ellipse) just clears and nothing happens. The two forms are not being associated. 
![selection_043](https://user-images.githubusercontent.com/33980111/36446586-73cac44a-168a-11e8-9931-2012b04278a0.png)

Right now the only two things the plugin does is 
1. hide forms in admin for other languages than the one currently displayed (unless "Show all languages" is selected) and 
2. display this warning: "Warning: save contact forms translation in Polylang settings" Can't get rid of this warning no matter what I do. And it shows on each screen in Admin. 

The warning leads me to Polylang settings. But there is nothing I can do there. The Foms are already checked and the checkmark is read-only: 
![image](https://user-images.githubusercontent.com/33980111/36446959-998b3a38-168b-11e8-836e-a2924dcd063b.png)

As it stands, I lose no functionality if I disable the plugin, on the contrary, as a bonus I get rid of the nagging warning.

**Comment by aurovrata** [comment]
please use the wordpress forum for general bug reporting.  Github is for specific code review & reporting of issues.  
Please read this [thread](https://wordpress.org/support/topic/not-compatible-with-cf7-v5/#post-9973288) in the wordpress support forum about your issue.
